name: CI
on: [pull_request]

jobs:
  test:
    strategy:
      fail-fast: false
      matrix:
        ruby-version:
          - "2.7"
          - "3.0"
          - "3.1"
          - "3.2"
        rails-version:
          - "7.0"
          - "6.1"
          - "6.0"
          - "main"
        exclude:
          - ruby-version: "2.7"
            rails-version: "main"
          - ruby-version: "3.2"
            rails-version: "6.0"

    env:
      RAILS_VERSION: ${{ matrix.rails-version }}

    name: ${{ format('Tests (Ruby {0}, Rails {1})', matrix.ruby-version, matrix.rails-version) }}
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Set up Ruby
        uses: ruby/setup-ruby@8a45918450651f5e4784b6031db26f4b9f76b251
        with:
          ruby-version: ${{ matrix.ruby-version }}
      - name: Install dependencies
        run: bundle install
      - name: Run linters
        run: bundle exec standardrb
      - name: Run migrations
        run: bundle exec rails db:migrate
      - name: Run tests
        run: bundle exec rails test
